### ISSUE TITLE
Replace Baobab with Redux

### ISSUE THREAD

**Issue by clebert** [clebert/universal-react-boilerplate#2]
https://github.com/gaearon/redux

**Comment by clebert** [comment]
https://medium.com/@dan_abramov/the-evolution-of-flux-frameworks-6c16ad26bb31

**Comment by clebert** [comment]
https://www.youtube.com/watch?v=xsSnOQynTHs

**Comment by why-jay** [comment]
Hi, I'm considering a similar switch from Baobab to Redux. How has it worked out for you? The main reason I want to switch is that Baobab still doesn't support hot-loading (and honestly losing in terms of popularity)

@Yomguithereal

**Comment by iLikeKoffee** [comment]
@clebert @chcokr https://github.com/iLikeKoffee/redux-boilerplate check that out. Feedback and PR's highly appreciated.
