### ISSUE TITLE
Fix hot reloading of action creators

### ISSUE THREAD

**Issue by clebert** [clebert/universal-react-boilerplate#20]
See https://github.com/gaearon/babel-plugin-react-transform/issues/26

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!
